module AllModuleTests(main) where

import Analysis.DependenceAnalysisTests
import Analysis.LoopAnalysisTests
import Analysis.PossibleLoopNestsTests
import Analysis.ReachingAssignments.RegisterTests
import Analysis.RegisterLivenessTests
import Analysis.RegisterReductionTests
import Analysis.RegisterSynonyms.RegisterTests
import Core.IndexExpressionTests
import Core.MatrixOperationTests
import Core.SyntaxTests
import FrontEnd.LexerTests
import FrontEnd.ParserTests
import Optimizations.CopyPropagationTests
import Optimizations.FullLoopUnrollingTests
import Optimizations.InnerLoopParallelizationTests
import Optimizations.LoopInvariantCodeMotionTests
import Optimizations.RegisterSynonymDeletionTests
import Optimizations.SiftLoopTests
import Testing.RestrictedLayoutTests
import Testing.TestCaseGenerationTests

main = do
  allCopyPropagationTests
  allDependenceAnalysisTests
  allFullLoopUnrollingTests
  allIndexExpressionTests
  allInnerLoopParallelizationTests
  allLexerTests
  allLoopAnalysisTests
  allLoopInvariantCodeMotionTests
  allMatrixOperationTests
  allParserTests
  allPossibleLoopNestsTests
  allReachingAssignmentsTests
  allRegisterLivenessTests
  allRegisterReductionTests
  allRegisterSynonymDeletionTests
  allRegisterSynonymsTests
  allRestrictedLayoutTests
  allSiftLoopTests
  allSyntaxTests
  allTestCaseGenerationTests
